# **Data Analysis with Python (NumPy) 1**

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## **NumPy Getting Started**

In [3]:
# importing library
import sys
import numpy as np

In [10]:
# Checking NumPy Version
print(np.__version__)

1.21.6


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## **NumPy Creating Arrays**

In [12]:
# We can create an Array by using array() function
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [13]:
# Define the type of variable by type() function
a = np.array([1, 2, 3, 4, 5])
print(type(a))

<class 'numpy.ndarray'>


In [14]:
# Creating 0-D array
a = np.array(10)
print(a)

10


In [15]:
# Creating 1-D array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [16]:
# Creating 2-D array
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [17]:
# Creating 3-D array
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [18]:
# Check Number of Dimensions
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [22]:
# Higher Dimensional Arrays
a = np.array([1, 2, 3, 4], ndmin=5)
print(a)

print('Number of Dimensions :', a.ndim)

[[[[[1 2 3 4]]]]]
Number of Dimensions : 5


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## **NumPy Array Indexing**

In [23]:
# Get element from the following array
a = np.array([1, 2, 3, 4, 5])

print(a[0])

1


In [24]:
# Access 2-D Arrays
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('3nd element on 1st row: ', a[0, 2])

3nd element on 1st row:  3


In [25]:
# Access 3-D Arrays
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(a[0, 1, 2])

6


In [27]:
# Negative indexing
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd row: ', a[1, -1])

Last element from 2nd row:  10


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## **NumPy Array Slicing**

In [28]:
# Slice Elements from index 1 to index 5
a = np.array([1, 2, 3, 4, 5, 6, 7])

print(a[1:5])

[2 3 4 5]


In [29]:
# Slice Elements from index 4 to the end
a = np.array([1, 2, 3, 4, 5, 6, 7])

print(a[4:]) 

[5 6 7]


In [30]:
# Slice Elements from the beginning to index 4
a = np.array([1, 2, 3, 4, 5, 6, 7])

print(a[:4]) 

[1 2 3 4]


In [32]:
# Negative Slicing
a = np.array([1, 2, 3, 4, 5, 6, 7])

print(a[-4:-1])

[4 5 6]


In [39]:
# The basic slice syntax is i:j:k where i is the starting index, j is the stopping index, and k is the step
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:6:2])

[2 4 6]


In [40]:
# Here 2 is step value for slicing 
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [42]:
# Slicing 2-D Arrays. Here 0 = array , 1:4 = Elements range
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(a[0, 1:4])

[2 3 4]


In [18]:
# Here 0:3 = array range, 4 = Elements 
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[6, 7, 8, 9, 10]])

print(a[0:3, 4])

[ 5 10 10]


In [19]:
# Slicing both Arrays and Elements
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(a[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## **NumPy Data Types**

In [20]:
# Get the data type of an array object
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [21]:
# Get the data type of an array containing strings
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [29]:
# Create an array with data type string
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [27]:
# Create an array with data type 4 bytes integer
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [30]:
# Converting Data Type on Existing Arrays
# Change data type from float to integer by using 'i' as parameter value
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [31]:
# Change data type from float to integer by using int as parameter value
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [32]:
# Change data type from integer to boolean
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## **NumPy Array Copy vs View**

In [34]:
# Make a copy, change the original array, and display both arrays
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 0

print(arr)
print(x)

[0 2 3 4 5]
[1 2 3 4 5]


In [38]:
# Make a view, change the original array, and display both arrays
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 0

print(arr)
print(x)

[0 2 3 4 5]
[0 2 3 4 5]


In [44]:
# Make a view, change the view, and display both arrays
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 0

print(arr)
print(x)

[0 2 3 4 5]
[0 2 3 4 5]


In [41]:
# Print the value of the base attribute to check if an array owns it's data or not
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## **NumPy Array Shape**

In [45]:
# Print the shape of a 2-D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [47]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('Shape of Array :', arr.shape)

[[[[[1 2 3 4]]]]]
Shape of Array : (1, 1, 1, 1, 4)


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## **NumPy Array Reshaping**

In [48]:
# Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [49]:
# Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [51]:
# Check if the returned array is a copy or a view
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

# The example above returns the original array, so it is a view.

[1 2 3 4 5 6 7 8]


In [53]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [55]:
# Convert the array into a 1D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [57]:
# A copy of the input array, flattened to one dimension
arr = np.array([[1, 2, 3], [4, 5, 6]])

x = arr.flatten()

print(x)

[1 2 3 4 5 6]


In [58]:
# The ravel() function is used to create a contiguous flattened array
arr = np.array([[1, 2, 3], [4, 5, 6]])

x = arr.ravel()

print(x)

[1 2 3 4 5 6]


In [62]:
# Rotate array by rot90()
arr = np.array([[1,2], [3,4], [5,6]])
print(arr)

rotate = np.rot90(arr)
print('After rotation : \n', rotate)

[[1 2]
 [3 4]
 [5 6]]
After rotation : 
 [[2 4 6]
 [1 3 5]]


In [84]:
# Flip array by flip()
arr = np.array([[1,2], [3,4]])
print(arr)

x = np.flip(arr,0)
print('After flip :\n',x)

[[1 2]
 [3 4]]
After flip :
 [[3 4]
 [1 2]]


In [70]:
# Diagonal array by diag()
arr = np.array([1,2,3,4,5])
D = np.diag(arr)
print(D)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [77]:
# Using flip() function
F = np.flip(D)
print(F)

[[5 0 0 0 0]
 [0 4 0 0 0]
 [0 0 3 0 0]
 [0 0 0 2 0]
 [0 0 0 0 1]]


In [78]:
# Using fliplr() function
F = np.fliplr(D)
print(F)

[[0 0 0 0 1]
 [0 0 0 2 0]
 [0 0 3 0 0]
 [0 4 0 0 0]
 [5 0 0 0 0]]


In [79]:
# Using flipud() function 
F = np.flipud(D)
print(F)

[[0 0 0 0 5]
 [0 0 0 4 0]
 [0 0 3 0 0]
 [0 2 0 0 0]
 [1 0 0 0 0]]


In [89]:
# Using roll(arr,shift,axis) function
arr = np.arange(12)
a = np.roll(arr,2)
print(a)

# reshape 1D array to 2D array
ar = np.reshape(arr,(3,4))
print(ar)

# 1 unit down roll
b = np.roll(ar,1,0)
print(b)

# 1 unit right roll 
c = np.roll(ar,1,1)
print(c)


[10 11  0  1  2  3  4  5  6  7  8  9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]]
[[ 3  0  1  2]
 [ 7  4  5  6]
 [11  8  9 10]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## **NumPy Array Iterating**

In [90]:
# Iterate 1-D array
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [91]:
# Iterate 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [92]:
# Iterate on each scalar element of the 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [93]:
# Iterate 3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [94]:
# Iterate on each scalar element of the 3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [95]:
# Iterate 3-D array by nditer() function
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [96]:
# Iterating Array With Different Data Types
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [99]:
# Iterating With Different Step Size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:,::2]):
  print(x)

1
3
5
7


In [100]:
# Enumerated Iteration Using ndenumerate()
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [101]:
# Enumerate on 2D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## **NumPy Joining Array**

In [102]:
# Join two arrays
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [108]:
# Join two 2-D arrays 
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

#axis=0
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

#axis=1
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## **Joining Arrays Using Stack Functions**

In [115]:
# row colomn switching by stack()
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)


[[1 4]
 [2 5]
 [3 6]]


In [110]:
# To stack along rows by hstack()
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [111]:
# To stack along colomns by vstack()
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [116]:
# Stacking Along Height (depth)
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## **NumPy Splitting Array**

In [117]:
# Split the array in n parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [118]:
# Access the splitted arrays:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [119]:
# Split the 2-D array into three 2-D arrays.

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [124]:
# Split the 2-D array into three 2-D arrays along rows.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3,axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [125]:
# Using hsplit()

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [126]:
# Using vsplit()

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [128]:
# Using dsplit()

arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

newarr = np.dsplit(arr, 3)

print(newarr)

[array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]]]), array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]]]), array([[[ 3],
        [ 6],
        [ 9]],

       [[12],
        [15],
        [18]]])]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## **NumPy Searching Arrays**

In [129]:
# Find index by where()
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [130]:
# Find index of even value
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [131]:
# Find index of odd value
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 != 0)

print(x)

(array([0, 2, 4, 6]),)


In [137]:
# Search element on a sorted array by searchsorted()
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [146]:
# Search element from right
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [148]:
# Search multiple elements
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## **NumPy Sorting Arrays**

In [149]:
# Sort the array by sort()

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [150]:
# Sort the array alphabetically

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [151]:
# Sort a boolean array

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [152]:
# Sort a 2-D array

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## **NumPy Filter Array**

In [153]:
# Create an array from the elements on index 0 and 2

import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [154]:
# Create a filter array that will return only values higher than 10
arr = np.array([1,10,20,30,4,70,71,5,24])

filter_arr = []

for i in arr:
  if i>10:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True, False, True, True, False, True]
[20 30 70 71 24]


In [156]:
# Direct filter
arr = np.array([1,10,20,30,4,70,71,5,24])

filter_arr = arr > 10

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False False  True  True False  True  True False  True]
[20 30 70 71 24]


In [155]:
# Create a filter array that will return only even elements from the original array
arr = np.array([1,10,20,30,4,70,71,5,24])

filter_arr = []

for i in arr:
  if i%2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, True, True, True, True, False, False, True]
[10 20 30  4 70 24]


In [157]:
# Direct filter
arr = np.array([1,10,20,30,4,70,71,5,24])

filter_arr = arr%2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True  True  True  True  True False False  True]
[10 20 30  4 70 24]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)